# Don't print a new line at the start of the prompt
add_newline = true

[directory]
truncation_length = 20
truncation_symbol = "â€¦/"
truncate_to_repo = true
style = "#FFD700"

[ruby]
symbol = "ğŸ”º "

[c]
format = "via [$name $version]($style)"


# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
format="$symbol "
success_symbol = "[â¯](bold #32cd32)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](bold red) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
# style = "bold #ff8c00"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

