# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
format="$symbol "
success_symbol = "[â¯](bold #32cd32)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[â¯](bold red) "

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "#FFD700"

[ruby]
symbol = "ğŸ”º "

[c]
format = "via [$name $version]($style)"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
# style = "bold #ff8c00"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
disabled = true

[git_status]
disabled = true

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[username]
style_user = "bold blue"
# style_root = "black bold"
format = "[$userğŸŒ±]($style) "
disabled = false
show_always = true